# -*- coding: utf-8 -*-
"""Training Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qOiApiliAu1_nbYC0VAt1YLIN8ftu9iW

# 🧠 YOLOv8 Training with Roboflow Dataset
This notebook demonstrates how to download a dataset from Roboflow, structure it properly for YOLOv8, and train a model with advanced configurations.

**Step 1: Install & Import Required Libraries**
"""

!pip install ultralytics
!pip install supervision
import cv2
import numpy as np
import matplotlib.pyplot as plt
import supervision as sv
from ultralytics import YOLO

"""**Step 2: Download Dataset from Roboflow**"""

# Commented out IPython magic to ensure Python compatibility.
# 
# %%bash
# cd /content
# mkdir -p dataset2
# cd dataset2
# curl -L "https://universe.roboflow.com/ds/l0JdPqNrPx?key=mt2ji07rnR" -o roboflow.zip
# unzip -q roboflow.zip
# rm roboflow.zip

"""**Step 3: Load Base Model (YOLOv8n)**"""

# Automatically download and load the YOLOv8n model
model = YOLO('yolov8n.pt')  # Use yolov8n.yaml if you want to customize architecture

"""**Step 4: Train the Model**"""

model.train(
    data='/content/dataset2/data.yaml',  # ✅ YAML with train/val/test paths and classes
    epochs=50,
    imgsz=896,
    batch=4,
    patience=30,
    workers=2,
    name='chicken_wide_farm_aug',
    device='cpu',  # Use 'cuda' if you have GPU

    # Optimizer & Scheduler
    lr0=2e-3,
    optimizer='AdamW',
    weight_decay=0.01,
    momentum=0.9,

    # Regularization
    dropout=0.2,

    # Aggressive Augmentations
    mosaic=1.0,
    mixup=0.5,
    copy_paste=0.2,
    hsv_h=0.02,
    hsv_s=0.8,
    hsv_v=0.5,
    degrees=10,
    translate=0.2,
    scale=0.7,
    shear=3.0,
    perspective=0.001,
    flipud=0.05,
    fliplr=0.5,

    # Save checkpoints every 10 epochs
    save_period=10
)

